//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public int id_venta { get; set; }
        public int id_producto { get; set; }
        public int id_cliente { get; set; }
        public double precio { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual producto producto { get; set; }
    }
}
